src/Entity/Maisons.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
/**
 * name space de validation // use Symfony\Component\Validator\Constraints as Assert;
 */
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
// pour 'limage a la une (10/16) on doit coller
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MaisonsRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
//par exemple me email unique UniqueEntity("email")
class Maisons
{

    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz',
        2 => 'Electrique & Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *      mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function __construct(){
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug() : String
    {
        // $slugify = new Slugify();
        // echo $slugify->slugify('Hello World!'); 
        
        // pour tout ecrire sur une ligne on fait
        //$slugify = (new Slugify())->slugify('Hello World!');

        // pour retouner le title avec un autre format
        return (new Slugify())->slugify($this->title);

    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice() : String
    {
        return number_format ($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType()
    {
        return SELF::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFilename(): ?string 
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return Maisons
     */
    public function setFilename(?string $filename): Maisons
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File 
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Maisons
     */
    public function setImageFile(?File $imageFile): Maisons
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


}

src/Controller/MaisonController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Notification\ContactNotification;
use App\Entity\Maisons;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Repository\MaisonsRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;

class MaisonController extends AbstractController
{
    /**
     * @var MaisonsRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    private $em;
    
    public function __construct(MaisonsRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em; 
    }
    
    
    /**
     * @Route("/maison", name="maison")
     */
    // public function index() : Response
    // {
        /*
         * pour injecter les donner dans la bse 
         */
        // $property = new Maisons();
        // $property->setTitle('mon troisieme bien')
        //     ->setPrice(120000)
        //     ->setRooms(8)
        //     ->setBedrooms(5)
        //     ->setDescription('une petite description')
        //     ->setSurface(200)
        //     ->setFloor(6)
        //     ->setHeat(3)
        //     ->setCity('Paris')
        //     ->setAdresse('23 street boys')
        //     ->setPostalCode('75000');
        // $em = $this->getDoctrine()->getManager();
        // $em->persist($property);
        // $em->flush();
      

        /**
         * avant de faire le contructeur on utiliser cette methodes pour appeler le repository
         *  
         * $property = $this->getDoctrine()->getRepository(Maisons::class);
         * dump($property);
         * 
         */

        /*
         * Recuperer les lignes de la base de donner -- trouver l'id num un 
         */
        // $property = $this->repository->find(1);

        /*
         * find all les lignes
         */
        // $property = $this->repository->findAll(); 

        /**
         * find avec parametre avec findOneBy
         */
        //$property = $this->repository->findOneBy(['floor' => 4]);
        //dump($property);

        /*
         * Si on veut retourner toutes les maison non vendu on doit utiliser le findAll mais
         * pour fonctionner il faut creer une methode et elle se fait dans ce cas (MaisonsRepository)
         * findByExampleField. a voir
         */

         /**
          * une fois on a creer notre findAllVisible on l'utilise
          */
        
        // $property = $this->repository->findAllVisible(); // depuis MaisonsRepository
        
        /* le flush va detecter que le sold a ete change a 'true' et il va apporter les modifs 
        * la base de donnee et on doit supprimer le setSold et flush car elle a deja ete changer definitivemnet
        */
        //$property[0]->setSold(true);
        //$this->em->flush();

        // recuperer tt les biens depuis la BDD
        // $properties = $this->repository->findAllVisible();

    /**
     * @Route("/maison", name="maison")
     */
    public function index(PaginatorInterface $paginator, Request $request) : Response
    {
        // Apres la pagination on fais les champs de recherche donc les champs de filtre
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        //on lui demande de gerer la requete
        $form->handleRequest($request);

        //faire la pagination ça change comme quit
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1), /*page number par default c'est 1 ici*/
            // 12 /*limit par page 3x4*/
            9 /*limit par page 3x3*/
        );
        return $this->render('Maisons/Maison.html.twig', [
            'controller_name' => 'MaisonController',
            'current_menu'    => 'maison',
            'properties'      => $properties,
            'form'            => $form->createView()
        ]);
    }

    /**
     * @return Response
     * @Route("/maison/{slug}-{id}", name="maison.show", requirements={"slug" : "[a-z0-9\-]*"})
     */
    // public function show($slug, $id) : Response
    public function show(Maisons $property, string $slug, Request $request, ContactNotification $notification) : Response
    {   
        /**
         * si on fait pas les parametres slug et id et on fait maisons $property a la place
         * on peut supprimer la ligne de      find($id)
         */
        // $property = $this->repository->find($id);

        if ($property->getSlug() !== $slug)
        {
            return $this->redirectToRoute('maison.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug(),
            ], 301);
        }

        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            // on notify la personne et on gere son message
            $notification->notify($contact);
            $this->addFlash('success', 'Votre email a bien été envoyé');
            return $this->redirectToRoute('maison.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }

        return $this->render('Maisons/show.html.twig', [
            'controller_name' => 'MaisonController',
            'current_menu'    => 'maison',
            // envoyer les property a la vue
            'house'           => $property,
            'form'            => $form->createView()
        ]);
    }
}

templates/Maisons/Maison.html.twig
{% extends "base.html.twig" %}

{% block title 'Nos maisons en vente' %}

{% block body %}
<div class="jumbotron">
     <div class="container">
        {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col-md-3">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col-md-3">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.option) }}
                </div>
                <div class="col-md-1">
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
        {{ form_end(form) }}
     </div>
</div>
    <div class="container">
        <h1 class="text-center">Bienvenu dans notre site de vente</h1>
        <h2>Voir toutes nos maisons</h2>
        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'Maisons/_property.html.twig' %}
                </div>            
            {% endfor %} 
        </div>
        <div class="pagination justify-content-center">
            {{ knp_pagination_render(properties) }} 
        </div>
    </div>
{% endblock %}

templates/Maisons/_property.html.twig
<div class="card mb-4">
    <div class="card-body">
        {% if property.filename %}
            <!-- <img src="/images/properties/{{ property.filename }}" class="card-img-top" alt="image"> -->
            <!-- on peut auusi faire avc le VECH comme suit pour le meme resultat -->
            <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" 
                class="card-img-top" alt="card-img-top" style="width:100%; height:auto;">
        {% else %}
             <img src="{{ '/images/properties/MMA_maison-a-vendre.jpg' | imagine_filter('thumb') }}"  
                class="card-img-top" alt="image">
        {% endif %}
        <h5 class="card-title">
            <a href="{{ path('maison.show', {slug: property.slug, id:property.id}) }}">
                {{ property.title}}
            </a>    
        </h5>
        <p class="card-text">{{ property.surface }} m² - {{ property.city}} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size:2rem; font-weight:bold;">
            {{ property.formattedPrice }} €
        </div>
    </div>
</div>

templates/Maisons/show.html.twig
{% extends "base.html.twig" %}

{% block title house.title %}

{% block body %}
    <div class="jumbotron">
        <div class="container">

            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}

            {% if not form.vars.valid %}
                <div class="alert alert-danger">
                    Erreur, veuillez introduire des valeurs valides !
                </div>
            {% endif %}

            <div class="row">
                <div class="col-md-8">
                {% if house.filename %}
                    <!-- <img src="/images/properties/{{ house.filename }}" class="card-img-top" alt="image"> -->
                    <!-- on peut auusi faire avc le VECH comme suit pour le meme resultat -->
                    <img src="{{ vich_uploader_asset(house, 'imageFile') | imagine_filter('medium') }}" 
                        class="card-img-top" alt="card-img-top" style="width:100%; height:auto;">
                {% else %}
                    <img src="{{ '/images/properties/MMA_maison-a-vendre.jpg' | imagine_filter('medium') }}"  
                        class="card-img-top" alt="image">
                {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ house.title }}</h1>
                    <h2>{{ house.rooms}} pièces - {{ house.surface }} m²</h2>
                    <div class="text-primary" style="font-size:4rem; font-weight:bold;">
                        {{ house.getFormattedPrice }} €
                    </div>
                    <a href="#" class="btn btn-primary" id="contactButton"{% if form.vars.submitted %} style="display: none;"{% 
                        endif %}>Nous Contacter</a>
                    <div id="contactForm" class="mt-2"{% if not form.vars.submitted %} style="display: none;"{% endif %}>
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col">{{ form_row(form.firstname) }}</div>
                            <div class="col">{{ form_row(form.lastname) }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {{ form_rest(form) }} 
                        <div class="form-group">
                            <button class="btn btn-primary">Envoyer</button>
                        </div>                       
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">      
        <p>
            {{ house.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ house.surface}} m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ house.rooms}}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ house.bedrooms}}</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ house.floor}}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ house.heatType}}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>spécificités</h2>
                <ul class="list-group">
                    {% for options in house.options %}
                        <li class="list-group-item">{{ options.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}